### PR TITLE
Refactor WeChatClient, wrap it as WeChat struct

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by messense** [comment]
@homu r+

**Comment by messense** [comment]
@homu retry

**Comment by barosl** [comment]
Hi! Sorry for off-topic, but I noticed that this pull request was not recognized by Homu, so I wanted to know the reason.

It seems that there was a bug of the recently added "rebase rather than merge" feature, and it made Homu fail to test this repository. This bug is fixed now, but I want to check if my assumption is correct. Did you happen to turn on the feature on homu.io when you tried to use Homu?

Again, sorry for the noise, and thanks in advance!

**Comment by messense** [comment]
Yes, I was using the rebase feature.

**Comment by barosl** [comment]
Nice to know, thanks!

**Pull request merged**
